server:
  url: 'https://adachidb.net'
  port: 3000
  frontend: true
  dev_frontend: false
  openAPI: true
  banner: true

rateLimit:
  windowSeconds: 60
  limits:
    api:
      status: 120
      posts:
        random: 3000
        random10: 2000
        search: 1000
        all: 30
        export: 10
        exportAll: 2
        add: 200

backup:
  enable: true
  interval: 60
  keep: 3



